spring:
  application:
    name: image-audio-spring-ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1
          temperature: 0.7
          max-tokens: 2048