### Read the text
POST http://localhost:8080/speaker
Content-Type: application/json
Accept: audio/mpeg

{
  "text": "Anyway, I am going to rule y'all once!"
}

### Transcript the speech
POST http://localhost:8080/transcripter
Content-Type: multipart/form-data; boundary=speech

--speech
Content-Disposition: form-data; name="file"; filename="ai-will-rule.mpeg"
Content-Type: audio/mpeg

< ../src/main/resources/static/audio/ai-will-rule.mpeg
--speech--
